name: EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.2

      - name: Set up Terraform Cloud
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          echo "credentials \"app.terraform.io\" {
            token = \"$TF_API_TOKEN\"
          }" >> ~/.terraformrc

      - name: Initialize Terraform
        run: terraform init -debug

      - name: Validate Terraform
        run: terraform validate -debug

      - name: Plan Terraform
        run: terraform plan -debug