name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  ECR_REPOSITORY: sac-ecr-repo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: mvn package

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 892935461155.dkr.ecr.ap-southeast-1.amazonaws.com
          REPOSITORY: sac-ecr-repo
          IMAGE_TAG: 1.0.0
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.2

      - name: Set up Terraform Cloud
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          echo "credentials \"app.terraform.io\" {
            token = \"$TF_API_TOKEN\"
          }" >> ~/.terraformrc

      - name: Change terraform execution directory
        run: cd terraform

      - name: Change terraform execution directory
        run: pwd && ls

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan